import Head from 'next/head'
import Link from 'next/link'
import styles from './header.module.css'
function HeaderComponent(){
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta charset="utf-8"></meta>
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
            </Head>
            <h1 className={styles.headingText}>It's header</h1>
            <h4>navigation</h4>
            <ul>
                <li>
                    <Link href='/about-us'>About Page</Link> 
                </li>
                <li>
                    <Link href='/all/doc-page'>Doc Page</Link>
                </li>
                <li>
                    <Link href='/admin-dashboard'>Admin</Link>
                </li>
                <li>
                    <Link href='/user-profile'>User</Link>
                </li>
            </ul>
        </>
    )
}

export default HeaderComponent;
